# Site settings
title: Python Graph Theory
description: >- # this means to ignore newlines until "baseurl:"
  A collection of quick-n-dirty Python classes for building
  simple graphs. Hack, model, solve then recurse while learning
  to keeping only what works ;-)... Unless otherwise stated
  both documentation and code are shared under the
  "GNU AGPL version 3" license by default.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  S0AndS0

# Build settings
markdown: kramdown
# mathjax: true
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
